test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.ab3522bccfc6251b6990fc041b53ef5fb8a8bb51.name = "Upgrade from 10.0.6~ynh1"