#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="downstream.php" --destination="$install_dir/inc/downstream.php"

chmod 400 "$install_dir/inc/downstream.php"
chown "$app:$app" "$install_dir/inc/downstream.php"

ynh_config_add --template="local_define.php" --destination="$install_dir/local_define.php"

chmod 400 "$install_dir//local_define.php"
chown "$app:$app" "$install_dir//local_define.php"

#=================================================
# INSTALL THE DATABASE
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
	"php$php_version" bin/console glpi:database:install --db-host="localhost" \
		--db-name="$db_name" --db-password="$db_pwd" --db-user="$db_user" --reconfigure --no-interaction
	"php$php_version" bin/console glpi:config:set url_base "https://$domain$path"
	ynh_safe_rm "$install_dir/install/install.php"
popd

chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
