#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config files marketplace plugins"

#=================================================
# UPDATE THE DATABASE
#=================================================
ynh_script_progression "Updating the database..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app php$php_version bin/console system:check_requirements
	ynh_hide_warnings ynh_exec_as_app php$php_version bin/console db:update --no-interaction --no-telemetry --force
popd

chown -R $app:www-data "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# TIMEZONE CONFIGURATION
#=================================================
ynh_script_progression "Setting up time zones..."

if command -v mariadb-tzinfo-to-sql &> /dev/null; then
    TZ_TOOL="mariadb-tzinfo-to-sql"
else
    TZ_TOOL="mysql_tzinfo_to_sql"
fi

if command -v mariadb &> /dev/null; then
    DB_CLIENT="mariadb"
else
    DB_CLIENT="mysql"
fi

$TZ_TOOL /usr/share/zoneinfo/ | $DB_CLIENT -u root -D mysql

ynh_mysql_db_shell <<< "GRANT SELECT ON \`mysql\`.\`time_zone_name\` TO '$db_user'@'localhost'; FLUSH PRIVILEGES;"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
